services:
  - type: web
    name: trip-planner-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    nodeVersion: 18
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 3000